import kram.advent.utils.StringUtil;
import org.junit.jupiter.api.Test;

import static kram.advent.day8.ResonantCollinearity.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class ResonantCollinearityTest {

    private static final String resonantCollinearityInputTest1 = """
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
            """;

    @Test
    public void resonantCollinearityTest1() {
        char[][] chars = StringUtil.stringToCharArr(resonantCollinearityInputTest1);
        fillAntennasMap(chars);
        findAntinodes(chars);

        assertEquals(14, uniquePositions.size());
    }
}
